# -*- coding: utf-8 -*-
"""udemy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rn1_w69UYew1gI_bl_8KeUqtTWxYSsfo
"""

age = int(input("enter your age"))
working = age < 18 or age > 65

print(f"at {age}, you are usally not  working")

"""**LIST**"""

freinds = [("yasin", 30),("mujjuzi",29),("ssebandeke",5)]
freinds.append(["Ceaser",56])

print(freinds[2])

"""**SETS**"""

art_freinds = {"Rolf","Anne","Jen"}
science_freinds ={"Jen","Charles"}

art_but_science = art_freinds.difference(science_freinds)
science_but_art = science_freinds.difference(art_freinds)

print(art_but_science)
print(science_freinds)

art_freinds = {"Rolf","Anne","Jen"}
science_freinds ={"Jen","Charles"}

not_arts = art_freinds.symmetric_difference(science_freinds)
print(not_arts)

art_freinds = {"Rolf","Anne","Jen"}
science_freinds ={"Jen","Charles"}

not_arts = art_freinds.union(science_freinds)
print(not_arts)

art_freinds = {"Rolf","Anne","Jen"}
science_freinds ={"Jen","Charles"}

common_set = art_freinds.intersection(science_freinds)
print(common_set)

nearby_people = {'Rolf', 'Jen', 'Anna'}
user_friends = set()  # This is an empty set, like {}

freind = input('what is the name of your freind? : ')

user_friends.add(freind)

print(user_friends.intersection(nearby_people))

"""**Dictionaries **"""

friend = {"Yasin":24, "mujjuzi":25, "kautharah":50}
print(friend)

freinds = (
           {"name" : "Mujjuzi Yasin","age" : 29},
           {"name" : "Ssebandeke Abasi","age" : 35},
           {"name" : "Mulindwa Quraish","age" : 45}
)
print(freinds[0]["name"])

friend = [("Yasin",24), ("mujjuzi",25), ("kautharah",50)]
freinds_ages = dict(friend)
print(freinds_ages)

"""**SUM** and len()"""

grade = [10, 25, 56,100]
total = sum(grade)
length = len(grade)
average = total/length

print(f"The Average is {average}")

"""exe"""

lottery_numbers = {13, 21, 22, 5, 8}

players = [
    {'yasin' : "Mujjuzi Yasin",'numbers':{11, 2, 3, 8, 5, 6}},
    {'abasi' : "Ssebandeke Abasi",'numbers':{10, 21, 22, 5, 14}}
]
player1 = players[0]["yasin"]
numbers = players[0]["numbers"].intersection(lottery_numbers)
print(f"{player1} got {len(numbers)} numbers right")

player2 = players[1]["abasi"]
numbers = players[1]["numbers"].intersection(lottery_numbers)
print(f"{player2} got {len(numbers)} numbers right")

"""**JOINING **"""

freinds = ["Yasin","Mujjuzi","Ssebandeke","Kyasanku"]
separator = ",".join(freinds)
print(f"These are my freinds:{separator}")

"""if statement"""

freind = 'Yasin'
user_name = input("Enter your name")

if user_name == freind:
  print("hello, freind!")
else:
  print("Hello staranger")

freinds = ["Yasin","Mujjuzi","Ssemba"]
family = ["Mariam",'Abas','Zash']

user_name = input("Enter your name")

if user_name in freinds:
  print("hello Freind")
elif user_name in family:
  print("Hello family")
else:
  print("I dont know you")

"""WHILE LOOPS"""

user_input = input("Do you wih to run the program? (yes/no): ")

while user_input == "yes":
  print("we are running!")
  user_input = input("Do you wish to run the program?(yes/no)")
print("we sttopped running.")

user_input = input("Please chosose your manue.(p/q)")

while user_input != "q":
    if user_input == "p":
      print("Hello")
      user_input = input("Please chosose your manue.(p/q)")
print("end of the program")

"""**FOR LOOPS**"""

students = [
            {"name":"Roll", "grade" : 90},
            {'name' : 'Bob', 'grade' : 50},
            {'name' : 'Yasin', 'grade' : 98},
            {'name' : 'Abasi', 'grade' : 70}
]

for student in students:
  name = student["name"]
  grade = student["grade"]
  print(f"{name} has a grade of {grade}.")

"""FOR LOOP DESTRUCTION"""

freinds = [('yasin', 25),('Abas', 35),('Semba',56)]

for name, age in freinds:
  print(f"{name} is {age} years old")

"""FOR LOOP ITERATING OVER DIC"""

freind_ages = {('yasin', 25),('Abas', 35),('Semba',56)}

for name, age in freind_ages.items():
  print(f"{name} is {age} years old")

"""BREAK"""

cars = ["ok", "ok", "ok", "faulty", "ok", "ok"]

for status in cars:
  if status == "faulty":
    print("stop production")
    break
  print(f"This car is {status}")
  print("Shipping new car to customer")

"""CONTINUE"""

cars = ["ok", "ok", "ok", "faulty", "ok", "ok"]

for status in cars:
  if status == "faulty":
    print("we found faulty car")
    continue
  print(f"This car is {status}")
  print("Shipping new car to customer")

"""FIZZBUZZ CHALLENGE"""

numbers = list(range(1, 101))

for number in numbers:
    if number % 3 == 0:
        print("Fizz")
    elif number % 5 == 0:
        print("Buzz")
    elif number % 5 == 0 or number % 3 == 0:
        print("FizzBuzz")
    else:
        print(number)

"""ELSE"""

cars = ["ok", "ok", "ok", "faulty", "ok", "ok"]

for status in cars:
  if status == "faulty":
    print("we found faulty car")
    break
  print(f"This car is {status}")
  print("Shipping new car to customer")
else:
  print('All cars built succesfuly no faulty car')

"""FOR (PRIME NUMBERS)"""

for n in range(2, 10):
  for x in range(2, n):
    if n % x == 0:
      print(f"{n} equals {x} * {n//x}")
      break
  else:
    print(f"{n} is a prime number.")

"""list comprehesion"""

freinds = ["Yasin", "Abasi","Jen","ssemba"]
lower = [name.lower() for name in freinds]
print(lower)

freind = input("Enter your freind name: ")
freinds = ["Yasin", "Abasi","Jen","ssemba"]
freinds_lower = [name.lower() for name in freinds]

if freind.lower() in freinds_lower:\
  freind_titlecased = freind.title()
  print(f"{freind.title()} is one of your freinds.")

numbers = [0,1,2,3,4]
double_numbers = [number * 2 for number in numbers]
print(double_numbers)

double_numbers = [number * 2 for number in range(5)]
print(double_numbers)

freind_ages = [23,15,60,52,4]
age_strings = [f"My freind is {age} years old." for age in freind_ages]
print(age_strings)

ages = [22,25,23,26,28]
odds = [age for age in ages if age % 2 == 1]
print(odds)

freinds = ["yasin","Ssemba","Peter"]
guests = ["jose","Bob","Rolf","Michel"]

freinds_lower = []